version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 10
    reviewers:
      - "Joctory"
    assignees:
      - "Joctory"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group updates to reduce PR noise
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - "@*"
          - "eslint*"
          - "prettier"
          - "mocha"
          - "chai"
          - "nodemon"
        update-types:
          - "minor"
          - "patch"
      # Group production dependencies by type
      build-tools:
        patterns:
          - "terser"
          - "clean-css-cli"
        update-types:
          - "minor"
          - "patch"
      # Security updates get their own PRs (high priority)
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    # Automatically merge patch updates for dev dependencies
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "firebase*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Singapore"
    open-pull-requests-limit: 5
    reviewers:
      - "Joctory"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"